### ISSUE TITLE
Errors on fonts when running demo's

### ISSUE THREAD

**Issue by dimitrydhondt** [mono-company/bedrock-invoice-demo#1]
I'm getting a lot of errors on 'js','ttf','woff', etc.. when running the demo.

![screenshot 2016-01-06 at 11 57 49](https://cloud.githubusercontent.com/assets/6338317/12141076/d841c02c-b46c-11e5-86d0-654ace8f662a.png)

**Comment by dimitrydhondt** [comment]
No icons are shown in the screens.

**Comment by Wolfr** [comment]
Do you have `fontcustom` installed? The errors you are getting are weird but actually refer to 404s i.e. the icon files are not there.

**Comment by dimitrydhondt** [comment]
I did `gem install fontcustom`

**Comment by Wolfr** [comment]
What happens if you install the other prerequisites listed on the fontcustom repo (See linux): https://github.com/FontCustom/fontcustom ?

**Comment by Wolfr** [comment]
This is a pretty tough dependency since it depends both on ruby and then some extra things as well (fontforge).

We tried to contain everything as an `npm` module but we had severe problems with packages like https://www.npmjs.com/package/gulp-iconfont .

**Comment by dimitrydhondt** [comment]
Seems to have solved the icons issue.
